RMET-220 Local notification - Interval value is not updated with "None" value on Android devices
OutSystems/cordova-plugin-local-notifications pull request #19
Opened 2020-12-18 16:49 UTC by alexgerardojacinto

## Description
Updated recurrence now showing in notification list correctly

## Context
Fixes https://outsystemsrd.atlassian.net/browse/RMET-220

Changed update notification logic in native code (Android) so that when updating a notification and changing its recurrence, this new change appears in the notification info in the Get All Notifications screen.

## Type of changes

- [ ] Feature (change which adds functionality)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to new feature)
- [x] Fix (change which fixes an issue)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to fix)
- [ ] Performance (change which improves performance)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to performance improvement)
- [ ] Refactor (non-breaking change that is neither feature, fix nor performance)
- [ ] Style (non-breaking change that only affects formatting and/or white-space)

## Components affected
- [x] Android platform
- [ ] iOS platform
- [ ] JavaScript
- [ ] OutSystems

## Tests
Executed tests with P0 priority from the Test Plan

## Screenshots (if appropriate)

## Checklist

- [x] Pull request title follows the format `RNMT-XXXX <title>`
- [ ] Tests have been created
- [x] Code follows code style of this project
- [ ] CHANGELOG.md file is correctly updated
- [ ] Changes require an update to the documentation
	- [ ] Documentation has been updated accordingly

2020-12-21 08:10 UTC, vmfo22 requested changes

2020-12-21 08:10 UTC, vmfo22 commented on src/android/LocalNotification.java
> +                    e.printStackTrace();
You could add a log here with a message to be more clear what happened in case of failure

2020-12-21 21:26 UTC, vmfo22 approved these changes

2021-01-04 13:05 UTC, GFOutsystems approved these changes

2021-01-04 13:35 UTC, merged